### ISSUE TITLE
The road to vuerd 2

### ISSUE THREAD

**Issue by dineug** [vuerd/vuerd#172]
## UI Panel Extension Modularization  
If you have more features, your library will become too large and you need to be able to choose.  

### UI Related Issues List  
- [SQL-Query generator](https://github.com/vuerd/vuerd/issues/3)
- [Custom generate code](https://github.com/vuerd/vuerd-vscode/issues/94)  

I've implemented all the features I want, so I'm not motivated at the moment.

I don't know when the v2.0.0 task will start.

Maybe I'll work on it after my new pet project.

Currently, we are only going to do small bugs and maintenance.

If you have a feature you want, open the issue.

**Comment by dineug** [comment]
## TODO

- [x] Integrating with reactive system components #181 
- [x] Extension Panel API #182
- [x] Zoom Level Support #183

**Comment by SylannBin** [comment]
In the mean time, one could hack their way around the problem by tweaking the svg's styling in the extension's source code (rendering will update in real time).

file should be at the following path: `~/.vscode/extensions/dineug.vuerd-vscode-x.y.z/static/vuerd.min.js`

For example, one really basic way is to add some scaling to the .vuerd-canvas-svg class:

```css
  .vuerd-canvas {
    /* ... */
    transform: scale(0.9);
  }
```

It's not perfect but it can help if you need to momentarily get a higher overview and from there you may find your best tweak.
