### ISSUE TITLE
2021 Roadmap

### ISSUE THREAD

**Issue by dineug** [vuerd/vuerd#190]
## TODO
- v2
  - [x] Integrating with reactive system components #181
  - [x] Extension Panel API #182
  - [x] Zoom Level Support #183
- [x] Add options when creating SQL DDL
    - ex) Bracket
- [x] generate template [#94](https://github.com/vuerd/vuerd-vscode/issues/94)
- [x] chrome extension vuerd App - [https://vuerd.github.io/](https://vuerd.github.io/)
    - ex) ![vuerd App](https://user-images.githubusercontent.com/45829489/69156939-8c146b80-0b27-11ea-99ed-6f1b8ce3c3ae.gif)

**Comment by dineug** [comment]
Added @vuerd/plugin-generate-template.
Available in vuerd-vscode v0.9.3.
@guntribam

**Comment by guntribam** [comment]
I've just created some templates and it is working out fine. Thanks for this amazing work
